USE [master]
GO

/****** Object:  Database [FoodDeliveryDb]    Script Date: 19.2.2019 00:25:04 ******/
CREATE DATABASE [FoodDeliveryDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FoodDeliveryDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FoodDeliveryDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FoodDeliveryDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FoodDeliveryDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [FoodDeliveryDb] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FoodDeliveryDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FoodDeliveryDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FoodDeliveryDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FoodDeliveryDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FoodDeliveryDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FoodDeliveryDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [FoodDeliveryDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET RECOVERY FULL 
GO

ALTER DATABASE [FoodDeliveryDb] SET  MULTI_USER 
GO

ALTER DATABASE [FoodDeliveryDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FoodDeliveryDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FoodDeliveryDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FoodDeliveryDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FoodDeliveryDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FoodDeliveryDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FoodDeliveryDb] SET  READ_WRITE 
GO


